CREATE DATABASE LOGINDB;
USE LOGINDB;

CREATE TABLE tbl_user (
id INT NOT NULL PRIMARY KEY IDENTITY,
usuario VARCHAR(255) NOT NULL,
contrasena VARCHAR(255) NOT NULL
);

INSERT INTO tbl_user VALUES ('Admin', 'Admin');